import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import ExcelJS from "exceljs";
import { GoogleGenAI, Type } from "@google/genai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Gemini AI on the server where process.env is accessible
const genAI = process.env.GEMINI_API_KEY 
  ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })
  : null;

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route for AI Image Generation
  app.post("/api/generate-image", async (req, res) => {
    if (!genAI) {
      return res.status(500).json({ error: "Gemini API key is not configured on the server." });
    }

    try {
      const params = req.body;
      const prompt = `Create a high-fidelity, photorealistic interior design render of a custom furniture piece.
Type: ${params.type}
Dimensions: ${params.dimensions}
Material: ${params.material}
Finish: ${params.finish}
Storage: ${params.storage}
Style: ${params.style}
Color: ${params.color}

The image should look like a professional photography from an interior design magazine. Modern lighting, clean background.`;

      // @ts-ignore - Using the SDK pattern identified from original code
      const result = await genAI.models.generateContent({
        model: "gemini-2.0-flash",
        contents: [{ text: prompt }],
        config: {
          imageConfig: {
            aspectRatio: "1:1"
          }
        }
      });
      
      // Note: Image generation via text models using inlineData is model-specific. 
      for (const part of result.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return res.json({ image: `data:image/png;base64,${part.inlineData.data}` });
        }
      }

      res.status(500).json({ error: "No image was generated by the model." });
    } catch (error: any) {
      console.error("Image generation error:", error);
      res.status(500).json({ error: error.message || "Failed to generate image" });
    }
  });

  // API Route for AI BOM Generation
  app.post("/api/generate-bom", async (req, res) => {
    if (!genAI) {
      return res.status(500).json({ error: "Gemini API key is not configured on the server." });
    }

    try {
      const params = req.body;
      const prompt = `Generate a realistic Bill of Materials (BOM) for the following furniture design:
Type: ${params.type}
Dimensions: ${params.dimensions}
Material: ${params.material}
Finish: ${params.finish}
Storage: ${params.storage}
Style: ${params.style}
Color: ${params.color}

Return a JSON array of objects, each containing:
- item: Name of the part or material
- material: Specific material used
- qty: Numeric quantity
- unit: Unit of measurement (e.g., pcs, sqft, meters, kg)
- estimated_cost_per_unit: A sample numeric value for cost estimation.`;

      // @ts-ignore - Using the SDK pattern identified from original code
      const result = await genAI.models.generateContent({
        model: "gemini-2.0-flash",
        contents: [{ text: prompt }],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                item: { type: Type.STRING },
                material: { type: Type.STRING },
                qty: { type: Type.NUMBER },
                unit: { type: Type.STRING },
                estimated_cost_per_unit: { type: Type.NUMBER }
              },
              required: ["item", "material", "qty", "unit", "estimated_cost_per_unit"]
            }
          }
        }
      });

      res.json(JSON.parse(result.text || "[]"));
    } catch (error: any) {
      console.error("BOM generation error:", error);
      res.status(500).json({ error: error.message || "Failed to generate BOM" });
    }
  });

  // API Route for Excel Generation
  app.post("/api/generate-excel", async (req, res) => {
    try {
      const { projectName, materials, clientName } = req.body;

      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet("Bill of Materials");

      // Set columns
      worksheet.columns = [
        { header: "Item", key: "item", width: 25 },
        { header: "Material", key: "material", width: 20 },
        { header: "Qty", key: "qty", width: 10 },
        { header: "Unit", key: "unit", width: 10 },
        { header: "Cost per Unit (₹)", key: "cost", width: 15 },
        { header: "Total Line Cost (₹)", key: "total", width: 15 },
      ];

      // Styling Header
      worksheet.getRow(1).font = { bold: true };

      let grandTotal = 0;
      materials.forEach((m: any) => {
        const lineTotal = (m.qty || 0) * (m.cost || 0);
        grandTotal += lineTotal;
        worksheet.addRow({
          item: m.item,
          material: m.material,
          qty: m.qty,
          unit: m.unit,
          cost: m.cost,
          total: lineTotal,
        });
      });

      // Add Total Row
      const totalRow = worksheet.addRow({
        item: "GRAND TOTAL",
        total: grandTotal,
      });
      totalRow.font = { bold: true };
      
      // ₹ Currency formatting for cost and total columns
      worksheet.getColumn('cost').numFmt = '"₹"#,##0.00';
      worksheet.getColumn('total').numFmt = '"₹"#,##0.00';

      // Set headers for file download
      res.setHeader(
        "Content-Type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      );
      res.setHeader(
        "Content-Disposition",
        `attachment; filename=${projectName.replace(/\s+/g, "_")}_BOM.xlsx`
      );

      await workbook.xlsx.write(res);
      res.end();
    } catch (error) {
      console.error("Error generating Excel:", error);
      res.status(500).json({ error: "Failed to generate Excel" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
